apiVersion: v1
kind: Namespace
metadata:
  name: kagent
---
apiVersion: v1
kind: Secret
metadata:
  name: kagent-gemini
  namespace: kagent
type: Opaque
stringData:
  GOOGLE_API_KEY: YOUR_GOOGLE_API_KEY
---
apiVersion: kagent.dev/v1alpha2
kind: ModelConfig
metadata:
  name: gemini
  namespace: kagent
spec:
  apiKeySecret: kagent-gemini
  apiKeySecretKey: GOOGLE_API_KEY
  model: gemini-2.5-flash
  provider: Gemini
  gemini: {}
